--------------------------------------------------------
--  DDL for Table RPT_SANCION
--------------------------------------------------------

  CREATE TABLE "RECA_DB"."RPT_SANCION" 
   (	"CONSECUTIVO_REPORTE" VARCHAR2(30 BYTE), 
	"REGISTRO" NUMBER(10,0), 
	"INSCRIPCION" NUMBER(10,0) DEFAULT 0, 
	"NRO_CONTRATO" VARCHAR2(120 BYTE), 
	"NIT_PROPONENTE" VARCHAR2(15 BYTE), 
	"ACTO_ADMINISTRATIVO" VARCHAR2(40 BYTE), 
	"FECHA_ACTO_ADMINISTRATIVO" DATE, 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTADO" NUMBER(1,0), 
	"CUMPLIMIENTO" CHAR(1 BYTE), 
	"ACTO_REVOCACION" VARCHAR2(40 BYTE), 
	"FECHA_ACTO_REVOCACION" DATE, 
	"INDICADOR_ENVIO" NUMBER(1,0), 
	"TIPO_IDENTIFICACION" VARCHAR2(2 BYTE), 
	"FECHA_EJECUTORIA_ACTO_ADMIN" DATE, 
	"NRO_ACTO_SUSPENSION_TEMP" VARCHAR2(40 BYTE), 
	"FECHA_ACTO_SUSPENSION" DATE, 
	"NRO_ACTO_CONFIRMA_SANCION" VARCHAR2(40 BYTE), 
	"FECHA_ACTO_CONFIRMA_SANCION" DATE, 
	"OBSERVACIONES" VARCHAR2(256 BYTE), 
	"CODIGO_CAMARA" VARCHAR2(2 BYTE), 
	"CODIGO_LIBRO_REGISTRADO" VARCHAR2(2 BYTE), 
	"FECHA_INSCRIPCION" DATE, 
	"FECHA_RADICACION_RUE" DATE, 
	"NRO_RADICACION_RUE" NUMBER(8,0), 
	"SW_DECRETO734" NUMBER(1,0) DEFAULT (0), 
	"NIT_ENTIDAD" VARCHAR2(20 BYTE), 
	"SW_RUES" NUMBER(1,0) DEFAULT (0), 
	"NRO_CONTRATO_SECOP" VARCHAR2(20 BYTE), 
	"IMAGEN_ACTO" CLOB, 
	"NRO_ACTO_EJECUTORIA" VARCHAR2(40 BYTE), 
	"VIGENCIA_SANCION" DATE, 
	"FUNDAMENTO_LEGAL" VARCHAR2(512 BYTE), 
	"CONTRATO_RELACIONADO" CHAR(1 BYTE), 
	"INCUMPLIMIENTO_VIVIENDA" CHAR(1 BYTE)
   )
  TABLESPACE "RECADATA" 
  ;
 

   COMMENT ON COLUMN "RECA_DB"."RPT_SANCION"."NRO_CONTRATO_SECOP" IS 'Número de contrato de acuerdo al SECOP';
 
   COMMENT ON COLUMN "RECA_DB"."RPT_SANCION"."IMAGEN_ACTO" IS 'Imagen en formato binario base64 del acto administrativo a través del cual se impuso la sanción.';
 
   COMMENT ON COLUMN "RECA_DB"."RPT_SANCION"."NRO_ACTO_EJECUTORIA" IS 'Número del acto administrativo con el cual se impone la sanción.';
 
   COMMENT ON COLUMN "RECA_DB"."RPT_SANCION"."VIGENCIA_SANCION" IS 'Fecha hasta cuando la sanción está vigente.';
 
   COMMENT ON COLUMN "RECA_DB"."RPT_SANCION"."FUNDAMENTO_LEGAL" IS 'Fundamento legal.';
   
   ALTER TABLE RPT_SANCION 
ADD (NOMBRE_ENTIDAD VARCHAR2(500) );

ALTER TABLE RPT_SANCION 
ADD (MUNICIPIO_ENTIDAD NUMBER );

ALTER TABLE RPT_SANCION 
ADD (AREA_ENTIDAD VARCHAR2(200) );

COMMENT ON COLUMN RPT_SANCION.NOMBRE_ENTIDAD IS 'Nombre de la entidad que reporta';

COMMENT ON COLUMN RPT_SANCION.MUNICIPIO_ENTIDAD IS 'Código dane del municipio de la entidad que reporta';

COMMENT ON COLUMN RPT_SANCION.AREA IS 'Area de la entidad que reporta';

