


CREATE OR REPLACE FUNCTION F_FECHA_CORTE_INF_FIN 
(
  vregistro IN number,
  vagno IN number
) RETURN DATE AS 

FECHA_CORTE DATE;

BEGIN
	SELECT FECHA INTO FECHA_CORTE
  FROM RP_INF_FINANCIERA
  WHERE REGISTRO=vregistro
  AND ANO=vagno
  AND ROWNUM=1;

RETURN FECHA_CORTE;

END F_FECHA_CORTE_INF_FIN;