CREATE TABLE LIQUIDACIONES_CAMBIO_DOMICILIO 
(
  LIQUIDACION_LOCAL NUMBER 
, LIQUIDACION_RUES NUMBER 
, TIPO VARCHAR2(5) 
);

COMMENT ON COLUMN LIQUIDACIONES_CAMBIO_DOMICILIO.LIQUIDACION_LOCAL IS 'Número de la liquidación local generada';

COMMENT ON COLUMN LIQUIDACIONES_CAMBIO_DOMICILIO.LIQUIDACION_RUES IS 'Número de la liquidación generada en el rues';

COMMENT ON COLUMN LIQUIDACIONES_CAMBIO_DOMICILIO.TIPO IS 'Tipo de registro (RM, R)UP';
